stages:
  - testing
  - checking_vul
  - patching
  - building
  - pushing

test:
  image: maven:3.6.3
  only:
    - merge_request
  stage: testing         
  script:
    - export NO_PROXY=127.0.0.0/8,0.0.0.0,192.168.0.0/16,10.0.0.0/8,localhost,.us.oracle.com,.uk.oracle.com,.oraclecorp.com,.clusters.oci.oraclecloud.com,169.254.169.254,100.107.236.104,elasticsearch
    - export http_proxy=http://www-proxy-hqdc.us.oracle.com:80
    - export ftp_proxy=http://www-proxy-hqdc.us.oracle.com:80
    - export FTP_PROXY=http://www-proxy-hqdc.us.oracle.com:80
    - export https_proxy=http://www-proxy-hqdc.us.oracle.com:80
    - export HTTPS_PROXY=http://www-proxy-hqdc.us.oracle.com:80
    - export no_proxy=127.0.0.0/8,0.0.0.0,192.168.0.0/16,10.0.0.0/8,localhost,.us.oracle.com,.uk.oracle.com,.oraclecorp.com,.clusters.oci.oraclecloud.com,169.254.169.254,100.107.236.104,elasticsearch
    - export HTTP_PROXY=http://www-proxy-hqdc.us.oracle.com:80
    - mvn test

checking_vul:
  image: ilanssari/ovp:v1.3
  stage: checking_vul              
  only:
    - merge_request
  script:
    - vulcheck
  artifacts:
    paths:
    - pom.xml
    - deployment/app.yaml
    expire_in: 10 minutes
    when: on_failure

paching:
  image: ilanssari/ovp:v1.3
  stage: patching
  only:
    - merge_request
  before_script:
    - export REMOTE_URL=$(echo $(git config --get remote.origin.url | sed -E  's/(.*)@(.*)/\2/'))
    - git config --global user.email "ci.patcher@oracle.com"
    - git config --global user.name "CI Patcher"
    - unset HTTPS_PROXY ftp_proxy no_proxy https_proxy HTTP_PROX http_proxy HTTP_PROXY
  script:
    - patch
  when: on_failure
  needs: ["checking_vul"]

building:
  image: maven:3.6.3-jdk-11
  stage: building
  only:
    #refs:
    #  - tags
    #variables:
    #  - $CI_COMMIT_TAG != "flux-sync"
    - master
  script:
    - mvn package
    - tar -zcvf libs.tar.gz -C target/libs .
  artifacts:
    paths:
    - target/*.jar
    - libs.tar.gz

pushing:
  stage: pushing
  only:
    - master
  image:
    name: mgit/base:kaniko-executor-debug-stable
    entrypoint: [""]
  script:
    #- echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"root\",\"password\":\"$CI_TOKEN\"}}}" > /kaniko/.docker/config.json
    #- /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - export  HTTPS_PROXY=http://www-proxy-hqdc.us.oracle.com:80/
    #- echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"root\",\"password\":\"$CI_TOKEN\"}}}" > /kaniko/.docker/config.json
    - echo "{\"auths\":{\"https://index.docker.io/v2/\":{\"auth\":\"$DHPWD\"}}}" > /kaniko/.docker/config.json
    #- /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination ilanssari/helidon:1.0.4
