stages:
  - testing
  - checking_vul
  - patching
  - building
  - pushing
variables:
  VERSION_LOGIC: '(if [ "$${CI_COMMIT_TAG}" == "" ]; then echo "0.0.2"; else echo "$${CI_COMMIT_TAG}"; fi);'

test:
  image: maven:3.6.3
  only:
    - master
  stage: testing         
  script:
    - env
    - echo $VERSION_LOGIC