image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - whoami

build:
  only:
    - merge_request
  before_script:
    - pwd
  script:
    - ls
  stage: build
