image: python:latest

stages:
  - checking_vul
  - patching
  - building
  - pushing

variables:
  DOCKER_TLS_CERTDIR: ""

checking_vul:
  stage: checking_vul                 
  only:
    - merge_request
  script:
    - python3 -c "import handler; handler.vulcheck()"
  

paching:
  stage: patching
  only:
    - merge_request                 
  script:
    - echo "patching ..."
  when: on_failure
