image: python:3.8.2

stages:
  - checking_vul
  - patching
  - building
  - pushing

variables:
  DOCKER_TLS_CERTDIR: ""

checking_vul:
  stage: checking_vul                 
  only:
    - merge_request
  script:
    - python3 -c "import handler; handler.vulcheck()"
  artifacts:
    paths:
    - pomtest.xml
    expire_in: 21 minutes
    when: on_failure

paching:
  stage: patching
  only:
    - merge_request                 
  script:
    - python3 -c "import handler; handler.patche()"
  when: on_failure
