stages:
  - testing
  - checking_vul
  - patching

variables:
  patchit: 'false'

test:
  image: python:3.8.2
  stage: testing         
  script:
    - echo $patchit

checking_vul:
  image: python:3.8.2
  stage: checking_vul      
  script:
    - echo $patchit
    - export patchit=true
    - echo $patchit

paching and testing:
  image: python:3.8.2
  stage: patching
  script:
    - echo $patchit
  #except:
  #  variables:
  #    - $patchit =~ /true/i