image: python:latest

stages:
  - parsing_dependencies
  - checking_vul
  - patching
  - building
  - pushing

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - whoami

parse:
  only:
    - merge_request
  script:
    - python ./pom-parser.py
  stage: parsing_dependencies
