stages:
  - testing
  - checking_vul
  - patching

test:
  image: python:3.8.2
  stage: testing         
  script:
    - madazch

checking_vul:
  image: python:3.8.2
  stage: checking_vul      
  script:
    - madazch

paching and testing:
  image: python:3.8.2
  stage: patching
  script:
    - echo "daz"
  needs: ["checking_vul"]
  when: on_failure
  #except:
  #  variables:
  #    - $patchit =~ /true/i