image: python:latest

stages:
  - checking_vul
  - patching
  - building
  - pushing

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - whoami

checking_vul:                 
  only:
    - merge_request
  script:
    - python3 -c "import handler; handler.vulcheck()"
  stage: checking_vul

paching:                
  script:
    - echo "patching ..."
  when: on_failure
  stage: patching
