apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helidon-standalone-quickstart-mp
  namespace: web
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helidon-standalone-quickstart-mp
        version: v1
    spec:
      containers:
      - image: registry.ol.ol.v8o.oracledx.com/osscan/helidon-project:v1.0.7_patched
        imagePullPolicy: Always
        name: helidon-standalone-quickstart-mp
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gitlabcred
