name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ilanssari/helidon-project@vzn
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.1
          java-package: jdk
      - name: Maven test
        run: mvn test
        #run: ls